# Nome do Workflow
name: Build, Push to ACR, and Deploy to Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Este job único irá construir, enviar e fazer o deploy
  build_push_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # ADICIONADO: Permissão para autenticação segura com o Azure
      contents: read  # Permissão para fazer o checkout do código

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.20.2
          sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: tradingbotweb.azurecr.io
          username: tradingbotweb
          password: yEErniz3reuQc0HN/CWL5XLZPc9W4gauM4e5EWVyBJ+ACRCincUT # Senha exposta conforme solicitado

      - name: Build, Tag, and Push Docker image
        run: |
          # 1. Constrói a imagem usando docker-compose. O nome será 'trading_boot_java-app'
          docker-compose build
          
          # 2. Renomeia a imagem para o formato do seu ACR.
          docker tag trading_boot_java-app tradingbotweb.azurecr.io/tradingbotweb:latest
          docker tag trading_boot_java-app tradingbotweb.azurecr.io/tradingbotweb:${{ github.sha }}

          # 3. Envia as duas tags (latest e a do commit) para o ACR
          docker push tradingbotweb.azurecr.io/tradingbotweb --all-tags
      
      - name: Login to Azure (for Web App deployment)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C93D11F8BC624F43A0B9DF3815648FC2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_62146FC7112248A68D4083DD786ECCB2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3136949EC064D5BB78F9746507600F5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tradingboot' 
          slot-name: 'Production'
          images: 'tradingbotweb.azurecr.io/tradingbotweb:${{ github.sha }}'
