# Nome do Workflow
name: Build and Push Docker image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=2.20.2
          sudo curl -L "https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ibmectradingbot.azurecr.io
          username: ibmectradingbot
          password: MMmLuO2+SrAkXmago26al28yVvvcrGt1tQHd+Lr20y+ACRD1gr3O

      - name: Build, Tag, and Push Docker image
        run: |
          docker-compose build
          docker tag trading_boot_java-app ibmectradingbot.azurecr.io/tradingbot:v2
          docker push ibmectradingbot.azurecr.io/tradingbot:v2

